# Generated by Django 2.1.1 on 2018-09-18 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 3, 52, 16, 637863, tzinfo=utc)),
        ),
    ]
